accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register


urlpatterns = [
    path("login/", auth_view.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_view.LogoutView.as_view(template_name="registration/logged_out.html"),
        name="logout",
    ),
    path("register/", register, name="register"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path("accounts", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Post
from .views import index

app_name = "post"

urlpatterns = [
    path("", index),
    path("list/", post_list, name="post_list"),
    path(
        "detail/<int:pk>/",
        DetailView.as_view(model=Post, template_name="posts/detail.html"),
        name="post_detail",
    ),
    path("upload/", PostUploadView.as_view(), name="post_upload"),
    path("delete/<int:pk>/", PostDeleteView.as_view(), name="post_delete"),
    path("update/<int:pk>/", PostUpdateView.as_view(), name="post_update"),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_posts"
    )
    title = models.CharField(max_length=50, unique=True)
    photo = models.ImageField(
        upload_to="photos/%Y/%m/%d", default="photos/no_image.png"
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated"]

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d%H:%M:%S")

    def get_absolute_url(self):
        return reverse("post:post_detail", args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords not matched!")
        return cd["password2"]

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm


def register(request):
    if request.method == "POST":
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
            return render(
                request, "registration/register_done.html", {"new_user": new_user}
            )
    else:
        user_form = RegisterForm()

    return render(request, "registration/register.html", {"form": user_form})

posts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import redirect
from .models import Post


def index(request):
    return render(request, "posts/index.html")


def post_list(request):
    posts = Post.objects.all()
    return render(request, "posts/list.html", {"posts": posts})


class PostUploadView(CreateView):
    model = Post
    fields = ["title", "photo", "text"]
    template_name = "posts/upload.html"

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect("/list")
        else:
            return self.render_to_response({"form": form})


class PostDeleteView(DeleteView):
    model = Post
    success_url = "/list"
    template_name = "posts/delete.html"


class PostUpdateView(UpdateView):
    model = Post
    fields = ["title", "photo", "text"]
    template_name = "posts/update.html"

posts/templates/base.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, minimum-scale=0, maximum-scale=1.0"
    />
    <title>헤어질 결심 {% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% sass_src 'posts/css/main1.scss' %}" />
    <!-- script -->
    <script src="{% static 'posts/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'posts/js/script_main.js' %}"></script>
    <script src="{% static 'posts/js/scrolla.jquery.min.js' %}"></script>
    <script src="{% static 'posts/js/splitting.min.js' %}"></script>
  </head>
  <body>
    <div class="wrap">
      <!-- header -->
      <header>
        <div class="inner">
          <a href="#" class="gnbBtn">
            <span class="a"></span>
            <span class="b"></span>
          </a>
          <a href="#" class="logo">헤어질 결심</a>
          {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="contact">Logout</a>
          {% else %}
          <a href="{% url 'register' %}" class="contact">Signup</a>
          <span class="contact" style="padding: 10px"> </span>
          <a href="{% url 'login' %}" class="contact">Login</a>
          {% endif %}
        </div>
        <nav class="gnb">
          <ul>
            <li>
              <a href="#">CREW <span>Made</span></a>
            </li>
            <li>
              <a href="#">CREW <span>Ready</span></a>
            </li>
            <li>
              <a href="#">CREW <span>Design</span></a>
            </li>
            <li>
              <a href="#">CREW <span>Source</span></a>
            </li>
          </ul>
        </nav>
      </header>

      {% block content %} {% endblock %}

      <!-- footer -->
      <footer>
        <div class="inner">
          <h1 class="footerLogo">à</h1>
          <ul class="contact">
            <li>Carrer del Jardi Botànic 4, Palma De Mallorca, 07012</li>
            <li>+34 123 456 789 | abcd.com</li>
          </ul>
          <ul class="sns">
            <li><a href="#">INSTAGRAM</a></li>
            <li><a href="#">FACEBOOK</a></li>
            <li><a href="#">LINKEDIN</a></li>
          </ul>
        </div>
      </footer>
    </div>
  </body>
</html>

posts/templates/posts/delete.html
{% extends 'base.html' %} {% load static %} {% block title %}- Delete{% endblock
%} {% block content %}

<section class="introduce">
  <div>
    <div>
      <div>Do you want to delete {{ object }}?</div>
      <form action="" method="post">
        {{ form.as_p }} {% csrf_token %}
        <input type="submit" value="Confirm" />
      </form>
    </div>
  </div>
</section>

{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {{ object.text|truncatechars:10 }}
{% endblock %}

{% block content %}

  <section class="introduce">
    <div class="row">
      <div>
        <p><img src="{{ object.photo.url }}" style="width: 100%;" alt=""></p>
        <button type="button">
          {{ object.author.username }}
        </button>
        <p>{{ object.text|linebreaksbr }}</p>

        <a href="{% url 'post:post_delete' pk=object.id %}">Delete</a>
        <a href="{% url 'post:post_update' pk=object.id %}">Update</a>
      </div>
      <div>
        {% load disqus_tags %}
        {% disqus_show_comments %}
      </div>
    </div>
  </section>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <!-- contents -->
  <div class="contents">
    <section class="visual">
      <img class="mainBg" src="{% static 'posts/img/main.jpeg' %}" alt="main poster"/>
    </section>
    <section class="introduce">
      <div class="inner">
        <div class="img animate" data-animate="motion">
          <img src="{% static 'posts/img/introduce.jpeg' %}" alt="movie poster"/>
        </div>
        <div class="text animate" data-animate="motion" data-splitting>
          <h2 class="title animate" data-animate="motion">영화 소개</h2>
          <p>
            친절하고 예의 바른 형사 ‘해준’, 어느 날 산에서 벌어진 변사
            사건을 맡게 되었다.<br/>
            사망자의 아내 ‘서래’를 만난 후 의심과 묘한 관심의 감정을 동시에
            느끼게 된다.<br/>
            의심과 관심 사이, 둘 사이에서 벌어지는 우회 관계를 그린 수사
            멜로 영화<br/>
          </p>
          <a
              href="https://www.youtube.com/watch?v=A33AdB4u8GQ"
              target="_blank"
          >예고편 보러가기</a
          >
        </div>
      </div>
    </section>
    <section class="about">
      <div class="inner">
        <div class="text animate" data-animate="motion" data-splitting>
          <h2 class="title">영화 정보</h2>
          <div>
            <p>장르</p>
            로맨스, 멜로/드라마
            <p>감독</p>
            박찬욱
            <p>극본</p>
            정서경, 박찬욱
            <p>출연진</p>
            탕웨이, 박해일
          </div>
        </div>
        <div class="img animate" data-animate="motion">
          <img src="{% static 'posts/img/poster2.jpeg' %}" alt="movie poster"/>
        </div>
      </div>
    </section>
    <section class="synopsis">
      <div class="inner">
        <ul class="list">
          <li>
            <a href="#">
              <img src="{% static 'posts/img/synopsis_1.jpeg' %}" alt=""/>
              <span><b>마침내.</b></span>
            </a>
          </li>
          <li>
            <a href="#">
              <img src="{% static 'posts/img/synopsis_2.jpg' %}" alt=""/>
              <span>나는요... 완전히 <b>붕괴</b>됐어요.</span>
            </a>
          </li>
          <li>
            <a href="#">
              <img src="{% static 'posts/img/sectors_3.jpg' %}" alt=""/>
              <span>
                    다른 남자하고 <b>헤어질 결심</b>을 하려고... 했습니다.
                  </span>
            </a>
          </li>
          <li>
            <a href="#">
              <img src="{% static 'posts/img/synopsis_4.jpeg' %}" alt=""/>
              <span>
                    날 사랑한다고 말하는 순간 당신의 사랑이 끝났고,<br/>
                    당신의 사랑이 끝나는 순간 내 사랑이 시작됐죠.
                  </span>
            </a>
          </li>
        </ul>
        <div class="fix">
          <div class="text animate" data-animate="motion" data-splitting>
            <h2 class="title">줄거리</h2>
            <p>
              산 정상에서 추락한 한 남자의 변사 사건.<br/>
              담당 형사 '해준'(박해일)은<br/>
              사망자의 아내 '서래'(탕웨이)와 마주하게 된다.<br/>
            </p>
            <p>"산에 가서 안 오면 걱정했어요, 마침내 죽을까 봐."</p>
            <p>
              남편의 죽음 앞에서 특별한 동요를 보이지 않는 '서래'.<br/>
              경찰은 보통의 유가족과는 다른 '서래'를 용의선상에 올린다.<br/>
              '해준'은 사건 당일의 알리바이 탐문과 신문,<br/>
              잠복수사를 통해 '서래'를 알아가면서<br/>
              그녀에 대한 관심이 점점 커져가는 것을 느낀다.<br/>
            </p>
            <p>
              한편, 좀처럼 속을 짐작하기 어려운 '서래'는<br/>
              상대가 자신을 의심한다는 것을 알면서도<br/>
              조금의 망설임도 없이 '해준'을 대하는데….<br/>
            </p>
            <p>
              진심을 숨기는 용의자<br/>
              용의자에게 의심과 관심을 동시에 느끼는 형사<br/>
              그들의 헤어질 결심<br/>
            </p>
          </div>
        </div>
      </div>
    </section>
    <section class="sectors">
      <div class="inner">
        <div class="text animate" data-animate="motion" data-splitting>
          <h2 class="title">sectors</h2>
          <p>
            Luxury crew apparel curated across oceans,<br/>
            in private residences and at altitude.
          </p>
          <a href="#">explore</a>
        </div>
        <ul class="list animate" data-animate="motion">
          <li>
            <a href="#">
              <img src="{% static 'posts/img/sectors_1.jpg' %}" alt=""/>
              <h3>yachting</h3>
            </a>
          </li>
          <li>
            <a href="#">
              <img src="{% static 'posts/img/sectors_2.jpg' %}" alt=""/>
              <h3>aviation</h3>
            </a>
          </li>
          <li>
            <a href="#">
              <img src="{% static 'posts/img/sectors_3.jpg' %}" alt=""/>
              <h3>residence</h3>
            </a>
          </li>
        </ul>
      </div>
    </section>
    <section class="journal">
      <div class="inner">
        <h2>journal</h2>
        <ul class="list animate" data-animate="motion">
          <li>
            <a href="#">
              <p class="img"><img src="{% static 'posts/img/journal_1.jpg' %}" alt=""/></p>
              <p>
                정점에 오른 세계적인 거장<br/>
                두 배우의 뜨거운 케미스트리<br/>
              </p>
              <h3>THE HOLLYWOOD REPORTER</h3>
            </a>
          </li>
          <li>
            <a href="#">
              <p class="img"><img src="{% static 'posts/img/journal_2.jpg' %}" alt=""/></p>
              <p>
                눈을 뗄 수 없을 정도로<br/>
                모든 장면이 아름답게 느껴진다<br/>
              </p>
              <h3>싱글리스트 강보라 기자</h3>
            </a>
          </li>
          <li>
            <a href="#">
              <p class="img"><img src="{% static 'posts/img/journal_3.jpg' %}" alt=""/></p>
              <h3>arboremtum</h3>
              <p>
                London is seeing a new genre of private independent member’s
                clubs emerging, offering luxurious leisure and dining
                facilities, alongside unique working environment and, most
                importantly an emphasis on environmental and social change.
              </p>
            </a>
          </li>
          <li>
            <a href="#">
              <p class="img"><img src="{% static 'posts/img/journal_4.jpg' %}" alt=""/></p>
              <h3>protected species</h3>
              <p>
                Iconic British design with contemporary rainwear technology
                At Crew à la Mode, we are passionate about sustainability,
                timeless style and performance-led design and we are always
                looking for brands who share our ethos and goals, in order
                to either work with them or recommend them to our clients.
              </p>
            </a>
          </li>
        </ul>
      </div>
    </section>
  </div>

{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}- List{% endblock%}

{% block content %}
  <section class="list">
    {% for post in posts %}
    <div>
      <div>
        <h1>{{ post.title }}</h1>
        <p>
          <img src="{{ post.photo.url }}" style="width: 100%" alt="" />
        </p>
        <button type="button">{{ post.author.username }}</button>
        <p>{{ post.text|linebreaksbr }}</p>
        <p>
          <a href="{% url 'post:post_detail' pk=post.id %}">댓글 달기</a>
        </p>
      </div>
    </div>
    {% endfor %}
  </section>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Update{% endblock %}

{% block content %}

  <section class="introduce">
    <div class="row">
      <div>
        <form action="" method="post" enctype="multipart/form-data">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" value="Update">
        </form>
      </div>
    </div>
  </section>

{% endblock %}

posts/templates/posts/upload.html
{% extends 'base.html' %} {% load static %} {% block title %}- Upload{% endblock
%} {% block content %}

<section class="introduce">
  <div>
    <div></div>
    <div>
      <form action="" method="post" enctype="multipart/form-data">
        {{ form.as_p }} {% csrf_token %}
        <input type="submit" value="Upload" />
      </form>
    </div>
    <div></div>
  </div>
</section>

{% endblock %}